"""Add model_name to roadmaps

Revision ID: 503cd17d6bfa
Revises: 8ba5ff4e650f
Create Date: 2025-03-26 22:49:18.583273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503cd17d6bfa'
down_revision: Union[str, None] = '8ba5ff4e650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', 
                sa.Column('model_name', 
                        sa.String(), 
                        nullable=False, 
                        server_default="Llama-3-70B"))
    
    # Remove the server_default after all records have the value
    op.alter_column('roadmaps', 'model_name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'model_name')
    # ### end Alembic commands ###
