"""Add metrics table

Revision ID: 8ba5ff4e650f
Revises: 6648367126d4
Create Date: 2025-03-26 22:25:06.941386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba5ff4e650f'
down_revision: Union[str, None] = '6648367126d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('bleu_score', sa.Float(), nullable=False),
    sa.Column('rouge_1_f1', sa.Float(), nullable=False),
    sa.Column('rouge_2_f1', sa.Float(), nullable=False),
    sa.Column('rouge_l_f1', sa.Float(), nullable=False),
    sa.Column('bert_score_f1', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
